openapi: '3.0.2'
info:
  title: FastAPI
  version: '0.1.0'
paths:
  '/speak':
    post:
      summary: Given text, returns an audio file of the spoken text
      operationId: speak_speak_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IncomingText'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            audio/mpeg:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    IncomingText:
      title: IncomingText
      required:
        - text
      type: object
      properties:
        text:
          title: Text
          type: string
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
