openapi: "3.0.2"
info:
  title: "FastAPI"
  version: "0.1.0"
paths:
  "/":
    get:
      summary: "Hello"
      operationId: "hello__get"
      responses:
        "200":
          description: "Successful Response"
          content:
            application/json:
              schema: {}
